spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/ranjeetkumar274/configuration-properties
          clone-on-start: true
  application:
    name: 30-Config-Server
management:
  security:
    enabled: false