spring:
  application:
    name: 33-Spring-Security-O-Auth2.0

  security:
    oauth2:
      client:
        registration:
          github:
            client-id: -----
            client-secret: ----
